[package]
name = "lexflex-engine"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
description = "SEM1 semantic engine for lexFlex"

[dependencies]
serde.workspace = true
serde_json.workspace = true
ron = { workspace = true }
lexflex-language = { path = "../lexflex-language" }
lexflex-model = { path = "../lexflex-model" }
lexflex-lingua = { path = "../lexflex-lingua" }
lexflex-parser = { path = "../lexflex-parser" }
lexflex-store = { path = "../lexflex-store" }
thiserror.workspace = true
