[package]
name = "lexflex-generation"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
lexflex-language = { path = "../lexflex-language" }
lexflex-model = { path = "../lexflex-model" }
thiserror.workspace = true
serde.workspace = true

[dev-dependencies]
ron.workspace = true
