mod bound_scope;
mod context;
mod error;
mod free_variables;
mod goal;
mod goal_canonical;
mod goal_canonical_error;
mod goal_hash;
mod goal_validation;
mod occurs;
mod solution_order;
mod solver;
mod substitution;
mod unify;
mod unify_error;
mod unify_expression;
mod unify_outcome;
mod unify_variable;

pub use context::{UnificationContext, UnificationMode};
pub use error::SolveError;
pub use goal::{EvidencePolicy, LinguaGoal};
pub use goal_canonical_error::GoalCanonicalizationError;
pub use goal_hash::{canonical_goal_request_hash, canonical_goal_semantic_hash};
pub use goal_validation::{validate_goal, GoalValidationError};
pub use lexflex_model::TypeRelation;
pub(crate) use solution_order::query_solution_sort_key;
pub use solver::{LinguaSolver, QuerySolution};
pub use substitution::Substitution;
pub use unify::unify;
pub use unify_error::UnifyError;
pub use unify_outcome::{UnifyMismatch, UnifyOutcome};
